[family]
description = "Table that represents information about my family"

    [[family.columns]]
    name = "name"
    type = "String"
    [[family.columns]]
    name = "gender"
    type = "String"
    [[family.columns]]
    name = "birthday"
    type = "String"

[users_01]
description = "Table of user IDs, actions, and dates"

    [[users_01.columns]]
    name = "user_id"
    type = "Int64"
    [[users_01.columns]]
    name = "action"
    type = "Union{String, Missing}"
    [[users_01.columns]]
    name = "action_date"
    type = "Union{String, Missing}"

[items_03]
description = "table containing a list of dates and items ordered"

    [[items_03.columns]]
    name = "item_date"
    type = "String"
    [[items_03.columns]]
    name = "item"
    type = "Union{String, Missing}"

[users_05]
description = "Table of user acquiring products"

    [[users_05.columns]]
    name = "user_id"
    type = "Int64"
    [[users_05.columns]]
    name = "product_id"
    type = "Union{Int64, Missing}"
    [[users_05.columns]]
    name = "transaction_date"
    type = "Union{String, Missing}"

[transactions]
description = ""

    [[transactions.columns]]
    name = "sender"
    type = "INT1"
    [[transactions.columns]]
    name = "receiver"
    type = "INT0"
    [[transactions.columns]]
    name = "amount"
    type = "REAL0"
    [[transactions.columns]]
    name = "transaction_date"
    type = "TEXT0"

[transactions_02]
description = "Table of transactions between two users"

    [[transactions_02.columns]]
    name = "sender"
    type = "Int64"
    [[transactions_02.columns]]
    name = "receiver"
    type = "Union{Int64, Missing}"
    [[transactions_02.columns]]
    name = "amount"
    type = "Union{Float64, Missing}"
    [[transactions_02.columns]]
    name = "transaction_date"
    type = "Union{String, Missing}"
