[family]
description = "Table that represents information about my family"

[[family.columns]]
name = "name"
type = "String"

[[family.columns]]
name = "gender" 
type = "String"

[[family.columns]]
name = "birthday"
type = "String"

[users_01]

[[users_01.columns]]
name = "user_id"
type = "Int64"

[[users_01.columns]]
name = "action"
type = "Union{String, Missing}"

[[users_01.columns]]
name = "action_date"
type = "Union{String, Missing}"

[transactions_02]

[[transactions_02.columns]]
name = "sender"
type = "Int64"

[[transactions_02.columns]]
name = "receiver"
type = "Union{Int64, Missing}"

[[transactions_02.columns]]
name = "amount"
type = "Union{Decimals.Decimal, Missing}"

[[transactions_02.columns]]
name = "transaction_date"
type = "Union{String, Missing}"

[items_03]

[[items_03.columns]]
name = "dates"
type = "String"

[[items_03.columns]]
name = "item"
type = "Union{String, Missing}"

[users_04]

[[users_04.columns]]
name = "id"
type = "Int64"

[[users_04.columns]]
name = "action"
type = "Union{String, Missing}"

[[users_04.columns]]
name = "action_date"
type = "Union{String, Missing}"

[users_05]

[[users_05.columns]]
name = "user_id"
type = "Int64"

[[users_05.columns]]
name = "product_id"
type = "Union{Int64, Missing}"

[[users_05.columns]]
name = "transaction_date"
type = "Union{String, Missing}"
